services:
  marzban:
    image: gozargah/marzban:dev
    restart: always
    env_file: .env
    network_mode: host
    volumes:
      - /var/lib/marzban:/var/lib/marzban

  analytics:
    build: ./analytics
    environment: 
      - MY_SECRET_PASSWORD=abc123123123
    ports:
      - 8501:8501
    depends_on:
      - marzban
    volumes:
      - /opt/marzban/analytics:/app
      - /var/lib/marzban:/var/lib/marzban